config/routes.rb
Stipendium::Application.routes.draw do

  devise_for :users
  resources :items

  root :to => "items#index"

end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :description, :income, :int_1, :int_2, :int_3, :int_4, :int_5, :int_6, :int_7, :int_8, :str_1, :str_2, :str_3, :str_4, :str_5, :str_6, :str_7, :str_8, :text, :title
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :trackable, :rememberable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_filter :authenticate_user!, :except => [:index, :show]

  def index
    if params.has_key?('search_word')
      mask = '%' + params[:search_word] + '%'
      @items = Item.where("(items.title LIKE ? OR items.description LIKE ? OR items.text LIKE ?) AND items.income <= ?", mask, mask, mask, params[:item][:income])
    else
      @items = nil
    end
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(params[:item])
    if @item.save
      redirect_to @item, notice: 'Item was successfully created.'
    else
      render action: "new"
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update_attributes(params[:item])
    redirect_to @item, notice: 'Item was successfully updated.'
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.haml
= form_for(@item) do |f|

  .row-fluid
    .span6

      .field
        = f.label :title, 'Titel:'
        = f.text_field :title

      .field
        = f.label :income, 'Einkommen unter CHF:'
        = f.select(:income, [1000, 2000, 3000])

      .field
        = f.label :description, 'Beschreibung:'
        = f.text_area :description, :size => "50x10"

      .field
        = f.label :str_1, 'Textfeld 1:'
        = f.text_field :str_1

      .field
        = f.label :str_2, 'Textfeld 2:'
        = f.text_field :str_2

      .field
        = f.label :str_3, 'Textfeld 3:'
        = f.text_field :str_3

      .field
        = f.label :str_4, 'Textfeld 4:'
        = f.text_field :str_4

      .field
        = f.label :str_5, 'Textfeld 5:'
        = f.text_field :str_5

      .field
        = f.label :str_6, 'Textfeld 6:'
        = f.text_field :str_6

      .field
        = f.label :str_7, 'Textfeld 7:'
        = f.text_field :str_7

      .field
        = f.label :str_8, 'Textfeld 8:'
        = f.text_field :str_8

    .span6

      .field
        = f.label :text, 'Details:'
        = f.text_area :text, :size => "50x10"

      .field
        = f.label :int_1, 'Zahlenfeld 1:'
        = f.text_field :int_1

      .field
        = f.label :int_2, 'Zahlenfeld 2:'
        = f.text_field :int_2

      .field
        = f.label :int_3, 'Zahlenfeld 3:'
        = f.text_field :int_3

      .field
        = f.label :int_4, 'Zahlenfeld 4:'
        = f.text_field :int_4

      .field
        = f.label :int_5, 'Zahlenfeld 5:'
        = f.text_field :int_5

      .field
        = f.label :int_6, 'Zahlenfeld 6:'
        = f.text_field :int_6

      .field
        = f.label :int_7, 'Zahlenfeld 7:'
        = f.text_field :int_7

      .field
        = f.label :int_8, 'Zahlenfeld 8:'
        = f.text_field :int_8

  .actions
    = f.submit('Speichern', :class => 'btn')

app/views/items/edit.html.haml
= render 'form'

app/views/items/index.html.haml
- if @items.nil?
  %br
  %p Benutze die Suchfelder links um die passenden Resultate für deine Bedürfnisse zu erhalten.

- elsif @items == []
  Kein Treffer gefunden.
- else
  - @items.each do |item|

    - if user_signed_in?
      %a.thumbnail.well{:href => edit_item_path(item)}
        %h6= item.title
        %p= "Für Einkommen unter #{item.income} CHF"
        - if not item.description.empty?
          %p= item.description[0..200] + ' ...'
    - else
      %a.thumbnail.well{:href => item_path(item)}
        %h6= item.title
        %p= "Für Einkommen unter #{item.income} CHF"
        - if not item.description.empty?
          %p= item.description[0..200] + ' ...'

app/views/items/new.html.haml
= render 'form'

app/views/items/show.html.haml
%h3= @item.title

%h6 Für Einkommen unter CHF:
= @item.income

.row-fluid
  .span6

    %h6 Beschreibung:
    = @item.description

    %h6 Textfeld 1:
    = @item.str_1

    %h6 Textfeld 2:
    = @item.str_2

    %h6 Textfeld 3:
    = @item.str_3

    %h6 Textfeld 4:
    = @item.str_4

    %h6 Textfeld 5:
    = @item.str_5

    %h6 Textfeld 6:
    = @item.str_6

    %h6 Textfeld 7:
    = @item.str_7

    %h6 Textfeld 8:
    = @item.str_8

  .span6

    %h6 Details:
    = @item.text

    %h6 Zahlenfeld 1:
    = @item.int_1

    %h6 Zahlenfeld 2:
    = @item.int_2

    %h6 Zahlenfeld 3:
    = @item.int_3

    %h6 Zahlenfeld 4:
    = @item.int_4

    %h6 Zahlenfeld 5:
    = @item.int_5

    %h6 Zahlenfeld 6:
    = @item.int_6

    %h6 Zahlenfeld 7:
    = @item.int_7

    %h6 Zahlenfeld 8:
    = @item.int_8

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Stipendium
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = javascript_include_tag :defaults
    = csrf_meta_tags
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
  %body
    .container
      %h1 Stipendien Informationen HSG St. Gallen
      .row-fluid
        .span3.well.sidebar
          = form_tag(root_path, method: "get") do
            = label_tag(:search_word, "Stichwort:")
            = text_field_tag(:search_word)

            = label_tag(:income, 'Einkommen unter CHF:')
            = select('item', 'income', [1000, 2000, 3000])
            %br
            = submit_tag("Suchen", class: "btn btn-primary")

          %hr

          - if user_signed_in?
            = link_to('Neuer Eintrag' , new_item_path, :class => 'btn')
            %br
            %br
            = link_to('Abmelden' , destroy_user_session_path, :method => :delete, :class => 'btn')
          - else
            = link_to('Admin' , user_session_path, :class => 'btn btn-mini')

        .span9
          = yield